USE dw_superstore;

SELECT 'DIM_TEMPO' AS tabela, COUNT(*) AS registros FROM DIM_TEMPO
UNION ALL
SELECT 'DIM_PRODUTO', COUNT(*) FROM DIM_PRODUTO
UNION ALL
SELECT 'DIM_CLIENTE', COUNT(*) FROM DIM_CLIENTE
UNION ALL
SELECT 'DIM_ENVIO',   COUNT(*) FROM DIM_ENVIO
UNION ALL
SELECT 'FATO_VENDAS', COUNT(*) FROM FATO_VENDAS;

SELECT 
    COUNT(*) AS fk_tempo_invalidas
FROM 
    FATO_VENDAS f
LEFT JOIN 
    DIM_TEMPO t ON f.sk_tempo = t.sk_tempo
WHERE 
    t.sk_tempo IS NULL;